/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "uattributes.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(uprotocol_v1_UAttributes, uprotocol_v1_UAttributes, 2)









