/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_UPROTOCOL_V1_UCODE_PB_H_INCLUDED
#define PB_UPROTOCOL_V1_UCODE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Canonical Error codes for uProtocol APIs */
typedef enum _uprotocol_v1_UCode {
    /* Completes successfully */
    uprotocol_v1_UCode_OK = 0,
    /* Operation has been cancelled by the caller */
    uprotocol_v1_UCode_CANCELLED = 1,
    /* An unknown (but not critical) error has occurred */
    uprotocol_v1_UCode_UNKNOWN = 2,
    /* Passed arguments are invalid (ex. improperly formatted) */
    uprotocol_v1_UCode_INVALID_ARGUMENT = 3,
    /* Operation has expired (timeout) */
    uprotocol_v1_UCode_DEADLINE_EXCEEDED = 4,
    /* Operation cannot be completed because the requested entity was not
 found (ex. database lookup and the data is not found)
 Calling uE *MAY* retry the operation with back-off */
    uprotocol_v1_UCode_NOT_FOUND = 5,
    /* The calling uE requested to add/create something that already exists
 (ex. add to a database something that is already there) */
    uprotocol_v1_UCode_ALREADY_EXISTS = 6,
    /* The calling uE is authenticated but not permitted to call the API */
    uprotocol_v1_UCode_PERMISSION_DENIED = 7,
    /* The calling uE does not have valid authentication credentials for the API */
    uprotocol_v1_UCode_UNAUTHENTICATED = 16,
    /* The resource being accessed has been exhausted (ex. out of disk space, etc...) */
    uprotocol_v1_UCode_RESOURCE_EXHAUSTED = 8,
    /* The system (service) is in a state that it cannot handle the request
 Calling uEs *SHOULD NOT* retry till the system state has been corrected */
    uprotocol_v1_UCode_FAILED_PRECONDITION = 9,
    /* The operation was aborted, typically due to a concurrency issue such as
 a sequencer check failure or transaction abort
 Calling uEs *MAY* retry but at a higher frequency than UNAVAILABLE */
    uprotocol_v1_UCode_ABORTED = 10,
    /* A caller would typically iterating through the results from said API
 and can is expected to detect the end of the results (out of range) */
    uprotocol_v1_UCode_OUT_OF_RANGE = 11,
    /* Part or all of the requested operation has not been implemented yet */
    uprotocol_v1_UCode_UNIMPLEMENTED = 12,
    /* A serious internal error has not described by a known error code */
    uprotocol_v1_UCode_INTERNAL = 13,
    /* The operation is currently unavailable
 Calling uEs *MAY* retry with back-off */
    uprotocol_v1_UCode_UNAVAILABLE = 14,
    /* When an unrecoverable data loss or corruption has occurred */
    uprotocol_v1_UCode_DATA_LOSS = 15
} uprotocol_v1_UCode;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _uprotocol_v1_UCode_MIN uprotocol_v1_UCode_OK
#define _uprotocol_v1_UCode_MAX uprotocol_v1_UCode_UNAUTHENTICATED
#define _uprotocol_v1_UCode_ARRAYSIZE ((uprotocol_v1_UCode)(uprotocol_v1_UCode_UNAUTHENTICATED+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
