/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "uri.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(uprotocol_v1_UUri, uprotocol_v1_UUri, AUTO)


PB_BIND(uprotocol_v1_UUriBatch, uprotocol_v1_UUriBatch, AUTO)



